import type { ContextSnapshot, ElementTarget, InteractionEvent } from '@/types'
import { SECRET_ENV_VAR, parseViewport, quote, trimEllipsis } from './shared'

function locator(target: ElementTarget): string {
  switch (target.strategy) {
    case 'testId':
      return `page.getByTestId(${quote(target.value)})`
    case 'role': {
      const name = target.accessibleName ? trimEllipsis(target.accessibleName) : ''
      return name
        ? `page.getByRole(${quote(target.value)}, { name: ${quote(name)} })`
        : `page.getByRole(${quote(target.value)})`
    }
    case 'label':
      return `page.getByLabel(${quote(trimEllipsis(target.value))})`
    case 'placeholder':
      return `page.getByPlaceholder(${quote(trimEllipsis(target.value))})`
    case 'text':
      return `page.getByText(${quote(trimEllipsis(target.value))})`
    case 'css':
      return `page.locator(${quote(target.cssSelector)})`
  }
}

function fillValue(step: InteractionEvent): string {
  return step.masked
    ? `process.env.${SECRET_ENV_VAR} ?? ''`
    : quote(step.value ?? '')
}

function statement(step: InteractionEvent): string[] {
  if (step.type === 'navigation') {
    return [`await page.goto(${quote(step.value ?? '')});`]
  }

  if (!step.target) {
    if (step.type === 'keydown' && step.key) {
      return [`await page.keyboard.press(${quote(step.key)});`]
    }
    return []
  }

  const base = locator(step.target)

  switch (step.type) {
    case 'click':
      return [`await ${base}.click();`]
    case 'input': {
      const lines = step.masked ? [`// Value was redacted during capture.`] : []
      lines.push(`await ${base}.fill(${fillValue(step)});`)
      return lines
    }
    case 'change': {
      if (step.target.tagName === 'select') {
        return [`await ${base}.selectOption({ label: ${quote(step.value ?? '')} });`]
      }
      if (step.target.tagName === 'input' && (step.value === 'true' || step.value === 'false')) {
        return [`await ${base}.${step.value === 'true' ? 'check' : 'uncheck'}();`]
      }
      return [`await ${base}.fill(${fillValue(step)});`]
    }
    case 'submit':
      return [`// Form submitted: ${step.target.cssSelector}`]
    case 'keydown':
      return [`await ${base}.press(${quote(step.key ?? 'Enter')});`]
    default:
      return []
  }
}

function dedupeNavigation(steps: InteractionEvent[]): InteractionEvent[] {
  return steps.filter((step, index) => {
    if (step.type !== 'navigation') {
      return true
    }

    const previous = steps
      .slice(0, index)
      .reverse()
      .find((candidate) => candidate.type === 'navigation')

    return previous?.value !== step.value
  })
}

export function generatePlaywrightScript(snapshot: ContextSnapshot): string {
  const { environment, interactions, consoleErrors } = snapshot
  const steps = dedupeNavigation(interactions)
  const startUrl = steps.find((step) => step.type === 'navigation')?.value ?? environment.pageUrl

  const body: string[] = []
  const viewport = parseViewport(environment.viewportSize)

  if (viewport) {
    body.push(
      `  await page.setViewportSize({ width: ${viewport.width}, height: ${viewport.height} });`,
    )
  }

  body.push(`  await page.goto(${quote(startUrl)});`, '')

  let emittedFirstNavigation = false

  for (const step of steps) {
    if (step.type === 'navigation' && !emittedFirstNavigation && step.value === startUrl) {
      emittedFirstNavigation = true
      continue
    }

    for (const line of statement(step)) {
      body.push(`  ${line}`)
    }
  }

  const hasSecret = interactions.some((step) => step.masked)
  const header = [
    `// Generated by QA Context Snapper on ${new Date(snapshot.stoppedAt).toISOString()}`,
    `// ${environment.browser} ${environment.browserVersion} on ${environment.os}`,
  ]

  if (hasSecret) {
    header.push(
      `// A redacted value is read from process.env.${SECRET_ENV_VAR}. Set it before running.`,
    )
  }

  const lines = [
    ...header,
    `import { test, expect } from '@playwright/test';`,
    '',
    `test('Bug Reproduction', async ({ page }) => {`,
    `  const consoleErrors: string[] = [];`,
    ``,
    `  page.on('console', (message) => {`,
    `    if (message.type() === 'error') consoleErrors.push(message.text());`,
    `  });`,
    `  page.on('pageerror', (error) => consoleErrors.push(error.message));`,
    '',
    ...body,
  ]

  if (consoleErrors.length > 0) {
    lines.push(
      '',
      `  // The recording captured ${consoleErrors.length} console error(s).`,
      `  // This assertion fails while the bug is present and passes once it is fixed.`,
      `  expect(consoleErrors, 'the page should log no console errors').toEqual([]);`,
    )
  }

  lines.push('});', '')

  return lines.join('\n')
}
